# Architecture Workflow Configuration
name: architecture
description: "Collaborative architectural decision facilitation for AI-agent consistency. Replaces template-driven architecture with intelligent, adaptive conversation that produces a decision-focused architecture document optimized for preventing agent conflicts."
author: "BMad"

# Critical variables
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: How to load sharded documents (FULL_LOAD, SELECTIVE_LOAD, INDEX_GUIDED)
input_file_patterns:
  prd:
    description: "Product requirements and features"
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/index.md"
    load_strategy: "FULL_LOAD"
  epics:
    description: "Epic and story breakdown (optional - uses PRD FRs if not present)"
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/index.md"
    load_strategy: "FULL_LOAD"
  ux_design:
    description: "UX design specification (optional)"
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/index.md"
    load_strategy: "FULL_LOAD"
  document_project:
    description: "Brownfield project documentation (optional)"
    sharded: "{output_folder}/index.md"
    load_strategy: "INDEX_GUIDED"

# Module path and component files
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/3-solutioning/architecture"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
template: "{installed_path}/architecture-template.md"

# Knowledge bases for intelligent decision making
decision_catalog: "{installed_path}/decision-catalog.yaml"
architecture_patterns: "{installed_path}/architecture-patterns.yaml"
pattern_categories: "{installed_path}/pattern-categories.csv"

# Output configuration
default_output_file: "{output_folder}/architecture.md"

standalone: true

# Web bundle configuration for standalone deployment
web_bundle:
  name: "architecture"
  description: "Collaborative architectural decision facilitation for AI-agent consistency. Replaces template-driven architecture with intelligent, adaptive conversation that produces a decision-focused architecture document optimized for preventing agent conflicts."
  author: "BMad"

  # Core workflow files ({bmad_folder}/-relative paths)
  instructions: "{bmad_folder}/bmm/workflows/3-solutioning/architecture/instructions.md"
  validation: "{bmad_folder}/bmm/workflows/3-solutioning/architecture/checklist.md"
  template: "{bmad_folder}/bmm/workflows/3-solutioning/architecture/architecture-template.md"

  # Knowledge base files for decision making
  decision_catalog: "{bmad_folder}/bmm/workflows/3-solutioning/architecture/decision-catalog.yaml"
  architecture_patterns: "{bmad_folder}/bmm/workflows/3-solutioning/architecture/architecture-patterns.yaml"
  pattern_categories: "{bmad_folder}/bmm/workflows/3-solutioning/architecture/pattern-categories.csv"

  # Task dependencies
  adv_elicit_task: "{bmad_folder}/core/tasks/advanced-elicitation.xml"

  # Default configuration values (can be overridden during bundle setup)
  defaults:
    user_name: "User"
    communication_language: "English"
    document_output_language: "English"
    user_skill_level: "intermediate"
    output_folder: "./output"

  # Input/output configuration for web deployment
  default_output_file: "{output_folder}/architecture.md"

  # Complete file list - ALL files this workflow depends on
  web_bundle_files:
    # Core workflow files
    - "{bmad_folder}/bmm/workflows/3-solutioning/architecture/instructions.md"
    - "{bmad_folder}/bmm/workflows/3-solutioning/architecture/checklist.md"
    - "{bmad_folder}/bmm/workflows/3-solutioning/architecture/architecture-template.md"

    # Knowledge base data files
    - "{bmad_folder}/bmm/workflows/3-solutioning/architecture/decision-catalog.yaml"
    - "{bmad_folder}/bmm/workflows/3-solutioning/architecture/architecture-patterns.yaml"
    - "{bmad_folder}/bmm/workflows/3-solutioning/architecture/pattern-categories.csv"

    # Task dependencies (referenced in instructions.md)
    - "{bmad_folder}/core/tasks/workflow.xml"
    - "{bmad_folder}/core/tasks/advanced-elicitation.xml"
    - "{bmad_folder}/core/tasks/advanced-elicitation-methods.csv"
