# Domain Research Workflow Configuration
name: domain-research
description: "Collaborative exploration of domain-specific requirements, regulations, and patterns for complex projects"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/{bmad_folder}/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Module path and component files
installed_path: "{project-root}/{bmad_folder}/bmm/workflows/1-analysis/domain-research"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/template.md"

# Optional knowledge base (if exists)
domain_knowledge_base: "{installed_path}/domain-knowledge-base.md"

# Output configuration
default_output_file: "{output_folder}/domain-brief.md"

standalone: true

# Web bundle configuration for standalone deployment
web_bundle:
  name: "domain-research"
  description: "Collaborative exploration of domain-specific requirements, regulations, and patterns for complex projects"
  author: "BMad"

  # Core workflow files ({bmad_folder}/-relative paths)
  instructions: "{bmad_folder}/bmm/workflows/1-analysis/domain-research/instructions.md"
  template: "{bmad_folder}/bmm/workflows/1-analysis/domain-research/template.md"

  # Default configuration values (can be overridden during bundle setup)
  defaults:
    user_name: "User"
    communication_language: "English"
    document_output_language: "English"
    user_skill_level: "intermediate"
    output_folder: "./output"

  # Input/output configuration for web deployment
  default_output_file: "{output_folder}/domain-brief.md"

  # Complete file list - ALL files this workflow depends on
  web_bundle_files:
    # Core workflow files
    - "{bmad_folder}/bmm/workflows/1-analysis/domain-research/instructions.md"
    - "{bmad_folder}/bmm/workflows/1-analysis/domain-research/template.md"

    # Task dependencies (referenced in instructions.md)
    - "{bmad_folder}/core/tasks/workflow.xml"
