# Brainstorm Game Workflow Configuration
name: "brainstorm-game"
description: "Facilitate game brainstorming sessions by orchestrating the CIS brainstorming workflow with game-specific context, guidance, and additional game design techniques."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmgd/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
game_dev_experience: "{config_source}:game_dev_experience"
date: system-generated

# Module path and component files
installed_path: "{project-root}/_bmad/bmgd/workflows/1-preproduction/brainstorm-game"
template: false
instructions: "{installed_path}/instructions.md"

# Context and techniques for game brainstorming
game_context: "{installed_path}/game-context.md"
game_brain_methods: "{installed_path}/game-brain-methods.csv"

# CORE brainstorming workflow to invoke
core_brainstorming: "{project-root}/_bmad/core/workflows/brainstorming/workflow.yaml"

standalone: true

web_bundle:
  name: "brainstorm-game"
  description: "Facilitate game brainstorming sessions by orchestrating the CIS brainstorming workflow with game-specific context, guidance, and additional game design techniques."
  author: "BMad"
  instructions: "_bmad/bmgd/workflows/1-preproduction/brainstorm-game/instructions.md"
  template: false
  web_bundle_files:
    - "_bmad/bmgd/workflows/1-preproduction/brainstorm-game/instructions.md"
    - "_bmad/bmgd/workflows/1-preproduction/brainstorm-game/game-context.md"
    - "_bmad/bmgd/workflows/1-preproduction/brainstorm-game/game-brain-methods.csv"
    - "_bmad/core/workflows/brainstorming/workflow.yaml"
  existing_workflows:
    - core_brainstorming: "_bmad/core/workflows/brainstorming/workflow.yaml"
